#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd -c ~/.dotfiles/sxhkd/sxhkdrc &

getxresource() {
	echo $(xrdb -query | grep "${1}:" | awk '{print $NF}')
}

getcolors() {
	FOREGROUND=$(getxresource foreground)
	BACKGROUND=$(getxresource background)
	FOCUSED=$(getxresource focused)
	ACTIVE=$(getxresource active)
	FEEDBACK=$(getxresource feedback)
	BACKGROUND_IMAGE=$(getxresource background_image)
}

xrdb ~/.colors/default.theme

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         4
bspc config window_gap           8
bspc config top_padding          32
bspc config right_padding        8
bspc config left_padding         8
bspc config bottom_padding       8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

hsetroot -fill $BACKGROUND_IMAGE -tint "$FOREGROUND"

bspc config focused_border_color "$FOCUSED"
bspc config normal_border_color "$FOREGROUND"
bspc config active_border_color "$ACTIVE"
bspc config presel_feedback_color "$FEEDBACK"
