export ZSH=$DOTFILES/zsh
export fontpath="${XDG_DATA_HOME:-$HOME/.local/share}"/fonts

source $ZSH/colors.zsh

export FUNCTIONS_PATH=$ZSH/functions
export FPATH=$FUNCTIONS_PATH:$FPATH

# Loading different zsh functions
if [[ -d $FUNCTIONS_PATH ]]; then
    for func in $FUNCTIONS_PATH/*(:t); autoload -Uz $func
fi

[[ -e /etc/zsh_command_not_found ]] && source /etc/zsh_command_not_found

source $ZSH/fzf.zsh

# initialize autocomplete
autoload -U compinit && compinit

autoload -U colors && colors

prepend_path "/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
prepend_path /usr/local/sbin
prepend_path $DOTFILES/bin
prepend_path $HOME/bin
prepend_path /usr/local/lib/ruby/gems/2.6.0/bin
prepend_path /usr/local/opt/ruby/bin
prepend_path /opt/homebrew/bin

alias vim="nvim"
#alias ls="colorls"

setopt NO_BG_NICE
setopt NO_HUP
setopt NO_LIST_BEEP
setopt LOCAL_OPTIONS
setopt LOCAL_TRAPS
setopt PROMPT_SUBST

# history
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt EXTENDED_HISTORY
setopt HIST_REDUCE_BLANKS
setopt SHARE_HISTORY
setopt HIST_IGNORE_ALL_DUPS

setopt COMPLETE_ALIASES
setopt MENU_COMPLETE
# make terminal command navigation sane again
## Terminus

#Unicomp
bindkey "\E[1;2H" beginning-of-line
bindkey "\E[1;2F" end-of-line
# Mac internal keyboard
bindkey "^[[1~" beginning-of-line
bindkey "^[[4~" end-of-line
bindkey "^[f" forward-word
bindkey "^[b" backward-word

## Kitty
# Mac internal
bindkey "^[[1;3C" forward-word
bindkey "^[[1;3D" backward-word
bindkey "^[[D" beginning-of-line
bindkey "^[[C" end-of-line
bindkey "^[[1~" beginning-of-line
bindkey "^[[4~" end-of-line

# matches case insensitive for lowercase
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'

# pasting with tabs doesn't perform completion
zstyle ':completion:*' insert-tab pending

# default to file completion
zstyle ':completion:*' completer _expand _complete _files _correct _approximate

source $ZSH/utils.zsh
source $ZSH/prompt.zsh


#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/home/speter/.sdkman"
[[ -s "/home/speter/.sdkman/bin/sdkman-init.sh" ]] && source "/home/speter/.sdkman/bin/sdkman-init.sh"
