export ZSH=$DOTFILES/zsh

source $ZSH/colors.zsh

# Loading different zsh functions
if [[ -d $ZSH/functions ]]; then
    for func in $ZSH/functions/*(:t); autoload -U $ZSH/functions/$func
fi

[[ -e /etc/zsh_command_not_found ]] && source /etc/zsh_command_not_found

source $ZSH/fzf.zsh

# initialize autocomplete
autoload -U compinit && compinit

autoload -U colors && colors

prepend_path /usr/local/sbin
prepend_path $DOTFILES/bin
prepend_path $HOME/bin
prepend_path /usr/local/lib/ruby/gems/2.6.0/bin
prepend_path /usr/local/opt/ruby/bin

alias vim="nvim"
alias ls="colorls"

setopt NO_BG_NICE
setopt NO_HUP
setopt NO_LIST_BEEP
setopt LOCAL_OPTIONS
setopt LOCAL_TRAPS
setopt PROMPT_SUBST

# history
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt EXTENDED_HISTORY
setopt HIST_REDUCE_BLANKS
setopt SHARE_HISTORY
setopt HIST_IGNORE_ALL_DUPS

setopt COMPLETE_ALIASES
setopt MENU_COMPLETE
# make terminal command navigation sane again
# bindkey '^[^[[D' backward-word
# bindkey '^[^[[C' forward-word
# bindkey '^[[5D' beginning-of-line
# bindkey '^[[5C' end-of-line
# bindkey '^[[3~' delete-char
# bindkey '^?' backward-delete-char
# bindkey "^A" vi-beginning-of-line

# matches case insensitive for lowercase
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'

# pasting with tabs doesn't perform completion
zstyle ':completion:*' insert-tab pending

# default to file completion
zstyle ':completion:*' completer _expand _complete _files _correct _approximate

source $ZSH/utils.zsh
source $ZSH/prompt.zsh

